# Generated by Django 3.1.1 on 2021-01-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mLogin', '0010_featurepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
